# Generated by Django 6.0 on 2026-02-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец задачи'),
        ),
    ]
